
/*
This file is autogenerated from a helper script using pgn data.
*/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public static class OpeningBook
{
    public static readonly Dictionary<UInt64, List<XAction>> Table
        = new Dictionary<UInt64, List<XAction>>
    {
    };
}
